#define ARROW 224
#define NUMPAD 0
#define UP 72
#define DOWN 80
#define LEFT 75
#define RIGHT 77
#define ESC 27
#define ENTER 13
#define SPACE 32
#define Black 0
#define Blue 1
#define Green 2
#define Aqua 3
#define Red 4
#define Purple 5
#define Yellow 6
#define White 7
#define EASY 1
#define MEDIUM 2
#define HARD 3
#define gotoxy(x,y) printf("\033[%d;%dH", (y), (x))